In [1]:
import numpy as np

In [12]:
numbers=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
numbers.dtype


dtype('int64')

In [11]:

numbers.shape

(4, 4)

In [15]:
print(numbers[:,1])
print(numbers[3,:])

[ 2  6 10 14]
[13 14 15 16]


In [25]:
Mean=numbers.mean()
print(Mean)
print(numbers[numbers>Mean])


8.5
[ 9 10 11 12 13 14 15 16]


In [27]:
row=[5,6,7,8]
print(numbers+row)

[[ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]
 [18 20 22 24]]
